# Generated by Django 2.2.8 on 2020-01-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='assets/files/')),
            ],
        ),
    ]
