# Generated by Django 2.2.8 on 2020-01-14 07:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='filename',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
